"""
Sigma rule exporter — read the audit log, emit a Sigma rule per (module, technique).

Purple-team value: at engagement end the operator hands the blue team the
exact Sigma ruleset that would have caught their tradecraft. Pairs with the
existing /report markdown summary.

Each rule maps a technique to one or more high-fidelity detections drawn from
the per-technique `detections` field embedded in the generator modules.
"""
from dataclasses import dataclass

from .anti_forensics import (
    SUPPORTED_TECHNIQUES as AF_TECHS, generate_anti_forensics,
)
from .evasion import SUPPORTED_TECHNIQUES as EV_TECHS, generate_evasion
from .sandbox_evasion import (
    SUPPORTED_TECHNIQUES as SE_TECHS, generate_sandbox_evasion,
)


@dataclass
class SigmaRule:
    title: str
    technique: str
    module: str
    level: str            # informational / low / medium / high / critical
    mitre: list[str]
    detections: list[str]


_RISK_TO_LEVEL = {
    "LOW": "low",
    "MEDIUM": "medium",
    "HIGH": "high",
    "CRITICAL": "critical",
}


def _resolve(technique: str, module: str):
    """Return the EvasionResult / AntiForensicsResult / SandboxEvasionResult for the technique."""
    if module == "evasion" and technique in EV_TECHS:
        return generate_evasion(technique)
    if module == "anti_forensics" and technique in AF_TECHS:
        return generate_anti_forensics(technique)
    if module == "sandbox_evasion" and technique in SE_TECHS:
        return generate_sandbox_evasion(technique)
    return None


def _sigma_safe_id(module: str, technique: str) -> str:
    """Generate a stable Sigma rule id-fragment from module + technique."""
    return f"revshell-academy-{module}-{technique}".replace("_", "-")


def _to_sigma_yaml(rule: SigmaRule) -> str:
    detections_block = "\n".join(
        f"    {i+1}: '{d.replace(chr(39), chr(39)+chr(39))}'"
        for i, d in enumerate(rule.detections)
    )
    return (
        f"title: {rule.title}\n"
        f"id: {_sigma_safe_id(rule.module, rule.technique)}\n"
        f"status: experimental\n"
        f"description: |\n"
        f"  Generated by revshell-api during a red-team engagement. Detects the\n"
        f"  '{rule.technique}' technique in the {rule.module} module.\n"
        f"references:\n"
        f"  - https://attack.mitre.org/techniques/{rule.mitre[0].replace('.', '/')}/\n"
        f"author: revshell-academy purple-team export\n"
        f"date: 2026/05/13\n"
        f"tags:\n"
        + "".join(f"  - attack.{m.lower()}\n" for m in rule.mitre)
        + f"logsource:\n"
        f"  product: windows\n"
        f"  category: process_creation\n"
        f"detection:\n"
        f"  detection_strings:\n"
        f"{detections_block}\n"
        f"  condition: 1 of detection_strings.*\n"
        f"level: {rule.level}\n"
    )


def build_rules_from_audit(engagement_id: str | None = None) -> tuple[list[SigmaRule], str]:
    """
    Read core.audit's iter_records() output, dedupe by (module, technique),
    and emit one Sigma rule per unique pair. Returns (rules_list, yaml_text).

    Late-import audit to avoid pulling settings at module import time.
    """
    from core.audit import iter_records

    seen: set[tuple[str, str]] = set()
    rules: list[SigmaRule] = []

    for record in iter_records():
        if engagement_id and record.get("engagement_id") != engagement_id:
            continue
        module = record.get("module")
        technique = record.get("technique")
        if not module or not technique:
            continue
        key = (module, technique)
        if key in seen:
            continue
        seen.add(key)

        result = _resolve(technique, module)
        if result is None:
            continue
        risk = getattr(result, "risk", "MEDIUM").upper()
        level = _RISK_TO_LEVEL.get(risk, "medium")
        rules.append(SigmaRule(
            title=f"Detection — {module}/{technique}",
            technique=technique,
            module=module,
            level=level,
            mitre=getattr(result, "techniques", []) or ["T1027"],
            detections=getattr(result, "detections", []) or [
                f"see revshell-academy documentation for {module}/{technique}"
            ],
        ))

    yaml_text = "---\n".join(_to_sigma_yaml(r) for r in rules) or "# No matching audit records.\n"
    return rules, yaml_text
